### ISSUE TITLE
二维码过期了，可以再分享一下不，我想向前辈学习一下

### ISSUE THREAD

**Issue by yikesoftware** [UUUUnotfound/Navex_fixed#1]
二维码过期了，可以再分享一下不，我想向前辈学习一下

**Comment by UUUUnotfound** [comment]
你发一下微信号, 我拉你进群


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"赤道企鹅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 凌晨0:01
收件人:&nbsp;"UUUUnotfound/Navex_fixed"<Navex_fixed@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[UUUUnotfound/Navex_fixed] 二维码过期了，可以再分享一下不，我想向前辈学习一下 (#1)





 
二维码过期了，可以再分享一下不，我想向前辈学习一下

**Comment by UUUUnotfound** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"赤道企鹅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 凌晨0:01
收件人:&nbsp;"UUUUnotfound/Navex_fixed"<Navex_fixed@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[UUUUnotfound/Navex_fixed] 二维码过期了，可以再分享一下不，我想向前辈学习一下 (#1)





 
二维码过期了，可以再分享一下不，我想向前辈学习一下

**Comment by UUUUnotfound** [comment]
已经更新

**Comment by yikesoftware** [comment]
> 已经更新

thanks
