### ISSUE TITLE
Groovy dependencies in python-joern

### ISSUE THREAD

**Issue by EdoardoVignati** [UUUUnotfound/Navex_fixed#2]
Hi and thank you for the patches!

I run neo4j with your example data. Then I tried to run _python-joern/static-main.py_ but I was facing the following problem:
```
Caught exception: <class 'py2neo.error.BadInputException'> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [unresolved dependency: com.github.jsqlparser#jsqlparser;1.1: not found, unresolved dependency: commons-net#commons-net;3.3: not found]
```
So I installed Groovy dependencies as you describe in your [guide](https://uuuunotfound.github.io/2020/05/03/%E5%A4%8D%E6%B4%BBNavex-%E4%BD%BF%E7%94%A8%E5%9B%BE%E6%9F%A5%E8%AF%A2%E8%BF%9B%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90/):
```
sudo snap install groovy --classic
grape -V install com.github.jsqlparser jsqlparser 1.1
grape -V install commons-net commons-net 3.3
```
but the problem still remain...Have you got any idea on what's going on? 

The error after the dep installation is slightly different: 

```
General error during conversion: Error grabbing Grapes -- [download failed: com.github.jsqlparser#jsqlparser;1.1!jsqlparser.jar(bundle)]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: com.github.jsqlparser#jsqlparser;1.1!jsqlparser.jar(bundle)]
```

I also tried to delete _~/.m2/_  and _~/.groovy/_ as suggested on stackoverflow.

Thank you

**Comment by UUUUnotfound** [comment]
Happy to help!

**Comment by EdoardoVignati** [comment]
@UUUUnotfound I tried to execute a fresh install of the environment as described in [your guide](https://uuuunotfound.github.io/2020/05/03/%E5%A4%8D%E6%B4%BBNavex-%E4%BD%BF%E7%94%A8%E5%9B%BE%E6%9F%A5%E8%AF%A2%E8%BF%9B%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90/index.html) in a new virtual machine.

The problem as described above still remain:

```
python main_test.py sql
Caught exception: <class 'py2neo.error.BadInputException'> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: com.github.jsqlparser#jsqlparser;1.1!jsqlparser.jar(bundle)]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: com.github.jsqlparser#jsqlparser;1.1!jsqlparser.jar(bundle)]
```

Any idea???

**Comment by UUUUnotfound** [comment]
my env version
```
ubuntu 16.04 LTS

ubuntu@ubuntu:~$ groovy --version
Groovy Version: 1.8.6 JVM: 1.8.0_252 Vendor: Private Build OS: Linux
```
if above not work
think about network

**Comment by EdoardoVignati** [comment]
I fixed. 

I suggest you to add the following steps in your guide.

The Groovy dependencies are downloaded into ~/.groovy/grapes so the correct way is to retrieve them from this local directory.

First of all I replaced the new version of Groovy with Groovy 1.8.6 downloading the binary [from here](https://bintray.com/version/files/groovy/maven/groovy/1.8.6)

Then I solved the above mentioned problem putting a config file into the groovy root ~/.groovy. 

In particular I followed [this gist](https://gist.github.com/marcelmaatkamp/341158)

``` 
Edit your $GROOVY_HOME/conf/groovy-start.conf and add the following line:

  load !{user.home}/.groovy/grapes/**.jar  
```

Anyway, your work is absolutely awesome! 

Thank you very much

**Comment by Lelouny** [comment]
@EdoardoVignati  Thanks for your idea! I followed your solution but still got one error:

`Traceback (most recent call last):
  File "main_test.py", line 4, in <module>
    from Analysis import Analysis
  File "/home/lwy/app/Navex_fixed/python-joern/Analysis.py", line 7, in <module>
    from joern.all import JoernSteps
  File "/home/lwy/app/Navex_fixed/python-joern/joern/all.py", line 3, in <module>
    from py2neo import Graph
ImportError: No module named py2neo`

But I am sure I have installed py2neo and its version is 2.0.8. Moreover, my neo4j version is 2.1.8.
Do you have any ideas?

**Comment by EdoardoVignati** [comment]
Hi @Lelouny , unfortunately I'm no longer working on this and I cannot help you at the moment.
